### ISSUE TITLE
[BUG] QR Code generates an http link instead of https

### ISSUE THREAD

**Issue by mariushosting** [Cirx08/WeddingShare#14]
I'm using reverse proxy and the QR Code automatically generates an http link instead of an https link.

**Comment by justindixson** [comment]
I can confirm this issue using traefik as a reverse proxy as well, it will redirect to https just fine after but that is due to my traefik rules.

**Comment by Cirx08** [comment]
@mariushosting @justindixson  This should be fixed now in v1.0.10 if you use the environment variable "FORCE_HTTPS". Can you please check and confirm?

**Comment by justindixson** [comment]
I can confirm that adding the new "FORCE_HTTPS" variable generates the QR code with HTTPS. Thanks!

**Comment by mariushosting** [comment]
> @mariushosting @justindixson This should be fixed now in v1.0.10 if you use the environment variable "FORCE_HTTPS". Can you please check and confirm?

Everything works like a charm now!
