### ISSUE TITLE
[Feature Request] Generate Thumbnails for Gallery View to Speed Page Loads

### ISSUE THREAD

**Issue by shumancw** [Cirx08/WeddingShare#17]
Gallery page loads seem to be quite slow. I assume that is because it's loading the full resolution image. Auto generate thumbnail views to speed page load.

**Comment by Cirx08** [comment]
There is a known issue on initial load coming from the DeviceDetector library that I have a fix planned for. Is this on initial load or every gallery load? Also how many images do you currently have in the gallery? I do also have pagination planned for this very reason but the thumbnail idea is also a good one that I'll add to the feature list.

**Comment by Cirx08** [comment]
Thumbnails and DeviceDetector caching is now implemented in the latest v1.1.0 release.
