### ISSUE TITLE
Photos that have been rotated to proper orientation display un-rotated

### ISSUE THREAD

**Issue by shumancw** [Cirx08/WeddingShare#18]
On iOS, uploads of photos that have been rotated show un-rotated on desktop browsers (Brave, Firefox, Edge), but correctly oriented on mobile browser.
![Screenshot 2024-12-05 100950](https://github.com/user-attachments/assets/7006bb59-36d3-4f28-90c6-89d84f38198d)

**Comment by Cirx08** [comment]
This should be fixed now if you upgrade to v1.1.1.

**Comment by Cirx08** [comment]
This should be fixed now if you upgrade to v1.1.1.

**Comment by shumancw** [comment]
> This should be fixed now if you upgrade to v1.1.1.

Well that was quick! Thanks!

**Comment by Cirx08** [comment]
Don't panic if they don't rotate straight away. It'll take up to a minute after getting the latest version for the background task to run and find any bad thumbnails and rotate them.
