### ISSUE TITLE
[Feature] - Gallery Photo Management

### ISSUE THREAD

**Issue by Cirx08** [Cirx08/WeddingShare#19]
- [x] Add the ability for an admin to delete approved images from a gallery.
- [x] Add the ability for an admin to wipe a gallery.
- [x] Add the ability for an admin to completely wipe all data.
- [x] Add the ability for an admin import and export a backup.
~~Add the ability for an admin to order gallery images.~~ (Moving to future release)
- [x] Add the ability for a gallery viewers order based on a dropdown (Upload Date, Date Taken, etc.).

**Comment by rehatiel** [comment]
Looking good so far!  I'd like to review the software when you're ready.

**Comment by Cirx08** [comment]
v1.2.0 is now released
