### ISSUE TITLE
[Feature Request] Allow Seconds In Cron

### ISSUE THREAD

**Issue by beakercs** [Cirx08/WeddingShare#20]
I find the delay for thumbnails to be generated too long, alot of users may incorrectly assume the broken images mean the photo did not upload correctly and retry multiple times, but the lowest value for DIRECTORY_SCANNER_INTERVAL is currently 1min (* * * * *).

NCrontab supports a 6 part cron which allows seconds to be specified:

`var schedule = CrontabSchedule.Parse(cron,
                              new CrontabSchedule.ParseOptions
                              {
                                  IncludingSeconds = true
                              });`

And it could be configured as:
`DIRECTORY_SCANNER_INTERVAL=0,30 * * * * *`

**Comment by Cirx08** [comment]
By any chance have you got REQUIRE_REVIEW=false? Going through the code I've missed this scenario and this would be a bug. The directory scanner would not be related to thumbnail generation under normal circumstances so the above suggestion shouldn't be required (although I will add it). The job of the directory scanner is meant for images that have not been uploaded but rather manually dropped into the directory. It picks up these images and adds them to the database and generates the thumbnail. For images uploaded through the front end thumbnails are generated upon review approval so I assume you have reviewing disabled and therefor the thumbnail should be generated at upload time.

**Comment by beakercs** [comment]
Yeah REQUIRE_REVIEW was disabled, that makes much more sense.
thanks!

**Comment by Cirx08** [comment]
I've just pushed the latest release (v1.2.0) which includes new features as well as a fix for this and seconds on the cron schedule.
