### ISSUE TITLE
Album url when single_album_mode true

### ISSUE THREAD

**Issue by mcfrojd** [Cirx08/WeddingShare#21]
When you setup an instance with single_album_mode: true, maybe the shared album could apper when you visit domain.com/
And admin login was at domain.com/Admin

Then you dont need to type anything in the "Gallery Selector" and
it should make it easier to vocally explain the url to the shared album.

**Comment by Cirx08** [comment]
I think this might over complicate the login flow as in most cases the user would still need to provide the secret key for the gallery. It also doesn't make it obvious to users how to get to the admin page without going through the documentation and manually updating the Url. I will need to have a think about a user friendly way to implement this workflow.

**Comment by mcfrojd** [comment]
Tested the latest 1.2.1, those changes was perfect for this issue!
