### ISSUE TITLE
[Feature Request] Mount Point Env Variable

### ISSUE THREAD

**Issue by jdeath** [Cirx08/WeddingShare#24]
In order to make this available to people using home assistant, be awesome if all the internal mount directories could be environment variables. In home assistant, only easy to remap a single directory to the host file system. Adding optional environment variables will allow easier integration. I had this working in an earlier version of WeddingShare, as only had a single mount location. But now with 3, it is not as easy to support. Thanks!

**Comment by Cirx08** [comment]
Could you please provide a bit more information on what you're trying to do and how this is achieved? I am familiar with Home Assistant but haven't ran it in years. Can HA run containers itself now? From my past experience it wasn't able to but this would have been achieved through the use of an iframe meaning the volume mappings would be something configured on the server and not through HA. Changing the mappings to environment variables wouldn't be straightforward and honestly sounds like a HA issue if it can't do docker volume mounts correctly.

**Comment by jdeath** [comment]
Yes, it totally is a Home Assistant issue!

HA can run containers, but they have to be turned into "addons" first. Usually it is just providing some extra information in a special configuration file and pointing to a dockerhub image. Some docker images can be run with no changes at all. Some you need to edit a few files in host image to reference how Home Assistant allows storage mapping. Once there is more than 1, it gets tricky. Often you can do a 'sed' on a config file inside the image and point the mounts to whatever you want inside the container. then I can map a single directory in the container to the host. Your source/config files are compiled, so I cannot do that.

Understand if don't want to make any changes. 

I have come across a few docker images allow you to specify an environment variable with the mounts, or use a configuration file to set the mounts. so you could specify. This would help, but totally understand if you would prefer not to.
```
THUMBNAIL_DIRECTORY: "/app/wwwroot/thumbnails"
CONFIG_DIRECTORY: "/app/config"
UPLOADS_DIRECTORY: "/app/wwwroot/uploads"
```
then I could point them to a single directory for my use (below I just need to map /app/config to the host):
```
THUMBNAIL_DIRECTORY: "/app/config/wwwroot/thumbnails"
CONFIG_DIRECTORY: "/app/config/config"
UPLOADS_DIRECTORY: "/app/config/wwwroot/uploads"
```

**Comment by Cirx08** [comment]
@jdeath the issue I have with this requests is I could add environment variables but I can't see a good way to achieve this. You would not be able to use the path "/app/config" as images etc. need to remain under the "/app/wwwroot" path to be servable resources. And similarly you would not want to change the path of your DB file to move it to the "/app/wwwroot" path as that would give access for bad actors to download your DB file.  Now with that being said I haven't tried this but in theory there's nothing stopping you doing the second point as you should be able to move it already by setting the "CONNECTION_STRING" environment variable to something like "Data Source=./wwwroot/wedding-share.db" although as stated above I don't recommend doing so. If you gave the above a try and it works and you are willing to accept the risks I will tweak the paths for uploads and thumbnails to allow you to move all to a "/app/wwwroot/config" path.

**Comment by jdeath** [comment]
ahh. I see. I will play with the CONNECTION_STRING and see if I can mount the other two directories separately. I agree, moving under wwwroot would be bad. I'll keep playing with it. Nice tool. I'll close.
