### ISSUE TITLE
[Feature Request] - Add Live Slideshow Viewing Mode

### ISSUE THREAD

**Issue by cschrch** [Cirx08/WeddingShare#25]
Introduce a slideshow viewing mode that allows automatic cycling through photos in the gallery. This would make it easy to display the photos on a projector or large screen during the wedding.

Key Features:
- Automatic Playback: Photos cycle through at a customizable interval (e.g., every 5–10 seconds).
- Full-Screen Mode: Optimized for large screens or projectors.
- Dynamic Content (Optional): Newly added photos are included automatically and prioritized to appear sooner than older ones, keeping the slideshow fresh.

**Comment by Cirx08** [comment]
@cschrch if you pull the latest v1.3.0 you will find a "Slideshow" option along the sidebar on a gallery. 

- You can configure the interval between slides using the "SLIDESHOW_INTERVAL" environment variable. 
- You can configure the transition between slides using the "SLIDESHOW_FADE" environment variable.
- You can configure how many slides to rotate through using the "SLIDESHOW_LIMIT" environment variable. Once the end slide is reached the page reloads (restarting the slideshow and getting the latest images) so for your 3rd request I suggest setting a value of say 50. I will possibly improve this feature in future if it gets more popularity.

**Comment by cschrch** [comment]
Thank you so much!
