### ISSUE TITLE
Slideshow, the images is of the screen

### ISSUE THREAD

**Issue by mcfrojd** [Cirx08/WeddingShare#26]
Love all the new additions to this project.
When i tried out the new slideshow feature my images end up a bit outside my browser window.
See attach screenshot.
![Screenshot KONTOR-MATTE 2024-12-17 10_1712](https://github.com/user-attachments/assets/52c5f6a8-e068-4688-ac6d-0645c542c366)

**Comment by Cirx08** [comment]
Can I please ask what your resolution is and if you have the zoom level set at 100% or are you zoomed out? Also I know it's a bit inconvenient but if you change the zoom or go full screen mode you would need to refresh the page for it to resize properly as the image size is detected and set on page load to make sure it fits the full height of the page.

**Comment by mcfrojd** [comment]
When i get home i can try to upload images into a fresh gallery

**Comment by mcfrojd** [comment]
v1.3.1 works like a charm
