### ISSUE TITLE
Read-only mode ?

### ISSUE THREAD

**Issue by accforgithubtest** [Cirx08/WeddingShare#3]
I have been looking for a lighter-weight photo wall application to share pics with my family, and happened to come across this. This looks neat and thank you for creating it.

I understand your reason for creating it, and including upload as a highlighted feature. I also however see a lot of potential for this to be a simple photo-wall application, that makes it easier to share with qr code.

With that context, would you please consider adding a "read-only" mode ? So the application will disable the upload section / not show it in the UI. Perhaps via an environment variable ?

We can simply mount an existing folder with pictures as a read-only volume on docker, and we have a nice photowall application, with a qr code to share it, and that would be great IMO. 
Keen to hear your thoughts, Cheers !

**Comment by PFindersDomain** [comment]
There is a "Disable_Upload" line in the appsetting.json file, does that not work?

**Comment by Cirx08** [comment]
Hi thanks for the comment. I'm guessing you didn't see it because I only added it yesterday in v1.0
3 but there is now a DISABLE_UPLOAD environment variables that will let you disable the upload field.

**Comment by accforgithubtest** [comment]
Yes, thank you, I am trying to use the DISABLE_UPLOAD variable now.

If I were to just point an existing folder full of photos to uploads, can I expect it to work ?
What would be the gallery name to input in the ` Please enter the name of the gallery you want to visit. ` screen ?

So far, the application is up and I am at the above screen, unsure how I can get the photos from the existing folder to show up on UI and what the gallery name would be ? Suggestions on how to proceed is highly appreciated! Cheers!

This is what I am trying to do in docker compose.
```
./photos/:/app/wwwroot/uploads:ro
```

**Comment by Cirx08** [comment]
@accforgithubtest I have now pushed v1.0.4. If you set SINGLE_GALLERY_MODE to true it should remove the option to select a gallery Id. Then map your volume to the default gallery using "./photos/:/app/wwwroot/uploads/default:ro"

**Comment by accforgithubtest** [comment]
It works perfectly fine now, 
Thank you so much for your effort and responses !
