### ISSUE TITLE
[Feature Request] Give the option to change default thumbnail size in the admin section as well as bulk approval/denial?

### ISSUE THREAD

**Issue by stayingarmed** [Cirx08/WeddingShare#31]
I know there is the THUMBNAIL_SIZE variable, but that seems to refer to the displaying of the images on the gallery. It would be nice to change JUST the THUMBNAIL_SIZE_ADMIN to be able to have smaller thumbnails in the admin section because currently it appears that the image is displayed in full-size or near full size so it takes up the whole screen and if there is multiple images to approve, that involves a lot of scrolling to get through the images.

Also, it would be nice to have a checkbox or button to approve everything in bulk if there is a lot that has been submitted.

Keep up the great work! Its nice to see changes being implemented so quickly when suggestions are made!

**Comment by Cirx08** [comment]
I went a different direction on this one. Have a look at v1.4.3 and see if that's any better. The gallery is condensed and there is a "Review" option at the top of the Admin page that allows you to bulk approve or reject all pending items.
