### ISSUE TITLE
[Feature Request] Option to disable upload for specific gallery

### ISSUE THREAD

**Issue by heig** [Cirx08/WeddingShare#32]
First of all: thanks for this amazing solution! Really great and easy to use. 

One FR that I would have is to give the ability, to disable uploading for a specific gallery. So in my use case I would like to create two galleries: 
- Preperations
- Party

The prepartions gallery is view-only for the guest, but they should not share images in there. The Party Gallery is than the gallery for them to share memories. 

Thanks :)

**Comment by Cirx08** [comment]
@heig if you pull v1.4.4 you should now be able to set DISABLE_UPLOAD_{GalleryId} = true to disable the upload feature on specific galleries. I have also added a few more gallery specific toggles which you can find in the readme.md.

**Comment by heig** [comment]
Amazing, that is really great. Thanks again!
