### ISSUE TITLE
Improve usability during upload process

### ISSUE THREAD

**Issue by brentschuddinck** [Cirx08/WeddingShare#33]
When uploading images, the label "uploading..." is displayed. When someone tries to upload many (larger) images, the upload process can take a few minutes and the user may think that the upload process is "freezing" while the upload is still in progress.

Some possible improvements:
- update label to "uploading image 3 from 21..."
- progress bar

**Comment by Cirx08** [comment]
@brentschuddinck pulling v1.4.5 should hopefully resolve this issue for you.

**Comment by brentschuddinck** [comment]
Thanks! Looks great 👍
