### ISSUE TITLE
Issue with upload text

### ISSUE THREAD

**Issue by LilSlippinJimmy** [Cirx08/WeddingShare#4]
The upload text says "Drag & amp ; Drop image(s) here to upload them to the gallery" Looks like it doesn't like the &. Also maybe change the text to "click here to upload" on mobile, as cannot drag and drop into the box on mobile devices.
![image](https://github.com/user-attachments/assets/5ce313c6-9625-412a-aaba-61b32e4b7cd3)

**Comment by Cirx08** [comment]
This should be fixed now in version 1.0.7
