### ISSUE TITLE
Unable to upload .heic files

### ISSUE THREAD

**Issue by LilSlippinJimmy** [Cirx08/WeddingShare#5]
I'm unable to upload .heic files (Apples default photo format), even with .heic added as an allowed file type. I've tried it out on my iPad, and by default, it does convert to .jpeg and it uploads. But if you try to upload it without converting and uploading as .heic, it doesn't upload. Also attempted on my windows desktop, and same behaviour.

**Comment by Cirx08** [comment]
Hey @LilSlippinJimmy, .heic is an Apple standard and browsers don't support it due to the licensing which is why your device defaults to converting it to .jpeg before upload. I could add code to allow the upload but the image will display as a broken image on the site. Do you want me to add an override for it? Again hitting home the point that it will only be visible if you downloaded the files to your local device for viewing so I see this as being a bit pointless.

**Comment by LilSlippinJimmy** [comment]
Ah, that's fair enough 😊I think it'd over complicate things if you added an override for heic, so i'd say leave it as it is then. Maybe add something about it in the readme. Thanks!

**Comment by CoffeePerry** [comment]
Hi, we could convert the uploaded image from _.heic_ format to a browser supported format like _.jpeg_ or _.png_.
At least for the preview shown in the browser, if we don't want to alter the original image stored on the server side.

**Comment by devnulluk** [comment]
Forgive my ignorance, could you handle it similar to how photoprism does?

https://docs.photoprism.app/developer-guide/media/heif/

**Comment by CoffeePerry** [comment]
Thanks for the suggestion and this is certainly a useful solution, but I was talking about making the _WeddingShare_ project autonomous, so that it automatically converts images to _.heic_ format.

**Comment by Cirx08** [comment]
The device already converts HEIC to JPEG upon upload which can then be viewed by all users. Converting server side would be pointless as its unnecessarily doing a job that the client can already do. As for only converting thumbnails and leaving the upload as HEIC this would lead to a bad user experience as when they click for the full view the image would break.

**Comment by CoffeePerry** [comment]
The device does not automatically convert _.heic_ to _.jpeg_ image when chosen from device gallery.
I also point out that from a Xiaomi POCO F2 Pro nothing happens when pressing the button in _WeddingShare_ to upload the image directly from the camera.
I agree that the client would have the ability to convert the image, but in reality the average user attempts to upload the image from the gallery using the appropriate button in _WeddingShare_, thus failing the upload.

> The device already converts HEIC to JPEG upon upload which can then be viewed by all users. Converting server side would be pointless as its unnecessarily doing a job that the client can already do. As for only converting thumbnails and leaving the upload as HEIC this would lead to a bad user experience as when they click for the full view the image would break.

**Comment by Cirx08** [comment]
@CoffeePerry this might be specific to Xiaomi devices (to which I do not own one to test) as all devices I have tested (Apple and Samsung) automatically convert to JPEG as they know the upload does not support the HEIC extension. 

Can you clarify what you mean by "using the appropriate button in WeddingShare, thus failing the upload." are you seeing an upload error message? If so can you please provide a screenshot of the issue.

As for "we could convert everything then: thumbnail and original image." why bother converting when the device can already upload in JPEG?

**Comment by CoffeePerry** [comment]
Sorry, the browser was missing permissions to access the camera, so pressing the button did not happen anything, now that I have granted permissions to access the camera by uploading the image directly from the camera the image is automatically converted as you told me before.
The problem remains that choosing the photo from the device's gallery is not automatically converted, as happens when shooting and uploading directly from the camera, for this reason i still worry about image conversion.

> [@CoffeePerry](https://github.com/CoffeePerry) this might be specific to Xiaomi devices (to which I do not own one to test) as all devices I have tested (Apple and Samsung) automatically convert to JPEG as they know the upload does not support the HEIC extension.
> 
> Can you clarify what you mean by "using the appropriate button in WeddingShare, thus failing the upload." are you seeing an upload error message? If so can you please provide a screenshot of the issue.
> 
> As for "we could convert everything then: thumbnail and original image." why bother converting when the device can already upload in JPEG?

**Comment by Cirx08** [comment]
> Sorry, the browser was missing permissions to access the camera, so pressing the button did not happen anything, now that I have granted permissions to access the camera by uploading the image directly from the camera the image is automatically converted as you told me before. The problem remains that choosing the photo from the device's gallery is not automatically converted, as happens when shooting and uploading directly from the camera, for this reason i still worry about image conversion.
> 
> > [@CoffeePerry](https://github.com/CoffeePerry) this might be specific to Xiaomi devices (to which I do not own one to test) as all devices I have tested (Apple and Samsung) automatically convert to JPEG as they know the upload does not support the HEIC extension.
> > Can you clarify what you mean by "using the appropriate button in WeddingShare, thus failing the upload." are you seeing an upload error message? If so can you please provide a screenshot of the issue.
> > As for "we could convert everything then: thumbnail and original image." why bother converting when the device can already upload in JPEG?

Can you please confirm for me that you don't have ".heic" in the allowed file types list as per the documentation doing so can prevent the image conversion from working. If you have the extension allowed the device thinks it is an accepted file type and uploads. If the extension is not in the list the device should recognise it is invalid and do the conversion even from the file picker.

**Comment by CoffeePerry** [comment]
I confirm that I have _.heic_ in the allowed file types list. Removing it instead makes the conversion happen automatically as you said.

> > Sorry, the browser was missing permissions to access the camera, so pressing the button did not happen anything, now that I have granted permissions to access the camera by uploading the image directly from the camera the image is automatically converted as you told me before. The problem remains that choosing the photo from the device's gallery is not automatically converted, as happens when shooting and uploading directly from the camera, for this reason i still worry about image conversion.
> > > [@CoffeePerry](https://github.com/CoffeePerry) this might be specific to Xiaomi devices (to which I do not own one to test) as all devices I have tested (Apple and Samsung) automatically convert to JPEG as they know the upload does not support the HEIC extension.
> > > Can you clarify what you mean by "using the appropriate button in WeddingShare, thus failing the upload." are you seeing an upload error message? If so can you please provide a screenshot of the issue.
> > > As for "we could convert everything then: thumbnail and original image." why bother converting when the device can already upload in JPEG?
> 
> Can you please confirm for me that you don't have ".heic" in the allowed file types list as per the documentation doing so can prevent the image conversion from working. If you have the extension allowed the device thinks it is an accepted file type and uploads. If the extension is not in the list the device should recognise it is invalid and do the conversion even from the file picker.

**Comment by CoffeePerry** [comment]
Good evening,
in version v1.7.2.5, if I select an image in .heic format from the gallery, it isn't automatically converted.
.heic isn't listed among the upload formats in the settings; in fact, this is the default setting. There are no server-side error logs.

**Comment by CoffeePerry** [comment]
https://github.com/Cirx08/WeddingShare/issues/146
