### ISSUE TITLE
Unraid template

### ISSUE THREAD

**Issue by delta0815** [Cirx08/WeddingShare#9]
Hey guys,
hey Cirx08,

what an amazing tool! Any plans to create an Unraid template for it?

Thanks for your consideration and best regards,

quicky

**Comment by Cirx08** [comment]
I don't use Unraid myself so I cannot comment on this but I believe a user has already created one - [Unraid Template](https://github.com/Cirx08/WeddingShare/issues/2) - [Unraid Community Store](https://unraid.net/community/apps/c/other?q=weddingshare#r)

![image](https://github.com/user-attachments/assets/e3c914c9-e49b-4d7f-b15f-a9c9c02dd460)

**Comment by delta0815** [comment]
WTF, this was so not expected, that I didn't even check the Community Store before posting. Amazing news and sorry for wasting your time!

Thanks again for such a great application!
